booktime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from main import views

urlpatterns = [
    path("contact-us/",views.ContactUsView.as_view(),name="contact_us"),
    path('about-us/', TemplateView.as_view(template_name='about_us.html'), name='about_us'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

main/models.py
from django.db import models

class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)

class Product(models.Model):
    tag = models.ManyToManyField('ProductTag', blank=True)
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    objects = ActiveManager()


    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product,on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to="product-images")
    thumbnail = models.ImageField(
        upload_to="product-thumbnails", null=True
    )

    def __str__(self):
        return self.product__name

class ProductTagManager(models.Manager):
    def get_by_natural_key(self,slug):
        return self.get(slug=slug)

class ProductTag(models.Model):
    
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)
    objects = ProductTagManager()

    def natural_key(self):
        return (self.slug,)

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from django.core.mail import send_mail
import logging

logger = logging.getLogger(__name__)

class ContactForm(forms.Form):
    name = forms.CharField(label='Your Name', max_length=100)

    message = forms.CharField(
        max_length=600, widget=forms.Textarea
    )

    def send_mail(self):
        logger.info("sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )

        send_mail(
            "Site message",
            message,
            "site@booktime.domain",
            ["customerservice@booktime.domain"],
            fail_silently=False,
        )

main/views.py
from django.views.generic.edit import FormView
from main import forms

class ContactUsView(FormView):
    template_name = "contact_form.html"
    form_class = forms.ContactForm
    success_url ="/"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

main/templates/about_us.html
{% extends 'base.html' %}

{% block content %}
<h2>About us</h2>
<p>BookTime is a company that sells books online.</p>

{% endblock content %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'css/Bootstrap.min.css' %}">
    <title>BookTime</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">BookTime</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggle-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item {% if request.path == '/about-us/' %}active{% endif %}">
                    <a class="nav-link" href="/about-us/">About us</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}

    <script src="{% static 'js/jquery.min.js' %}">
    </script>
    <script src="{% static 'js/popper.min.js' %}">
    </script>
    <script src="{% static 'js/bootstrap.min.js' %}">
    </script>
</body>

</html>

main/templates/contact_form.html
{% extends "base.html" %}

{% block content %}
<h2>Contact us</h2>
<p>Please fill the form below to contact us</p>
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form.name.label_tag }}
        <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" id="id_name" name="name"
            placeholder="Your name" value="{{ form.name.value|default:''}}">
        {% if form.name.errors %}
        <div class="invalid-feedback">
            {{ form.name.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.message.label_tag }}
        <textarea class="form-control {% if form.message.errors %}is-invalid{% endif %}" id="id_message" name="message"
            rows="3">
           {{ form.message.value|default:""}}
        </textarea>
        {% if form.message.errors %}
        <div class=" invalid-feedback">
            {{ form.message.errors }}
        </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}

main/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h2>Home</h2>
<p>this will be the content of the home</p>
{% endblock content %}